### PR TITLE
Ran pre-commit, added licenses

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by evaherrada** [comment]
@tannewt Any idea how to fix the Sphinx failure? I'm pretty sure I've run across this before and you told me how to fix it (although I could be mistaken)

**Comment by tannewt** [comment]
I'm not sure what annotations is. I'd ask @dhalbert who wrote that code.

**Comment by dhalbert** [comment]
`annotations` is type annotations, which are available as a `__future__` feature starting in Python 3.7. This library and the other BLE libraries depend on at least Python 3.7 for a number of things when run under `adafruit-blinka-bleio`. The rollback to Python 3.6 in the `.yml` files will break things.

**Comment by evaherrada** [comment]
(meant to write 3.7 not 3.6 on the first commit)

**Review by FoamyGuy — APPROVED** [review]

**Pull request merged**
